name: 'markdownlint-cli2-action'
author: 'David Anson'
description: 'A GitHub Action to run the markdownlint-cli2 tool for linting Markdown/CommonMark files with the markdownlint library'
branding:
  icon: 'check-square'  
  color: 'orange'
inputs:
  globs:
    description: 'Glob expression(s) of files to lint (newline-delimited)'
    default: '*.{md,markdown}'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
