name: markdownlint-cli2-action
author: David Anson
description: A GitHub Action to run the markdownlint-cli2 tool for linting Markdown/CommonMark files with the markdownlint library
branding:
  icon: check-square
  color: orange
inputs:
  command:
    description: Command to run (unset, "fix", or "config")
    default: ''
    required: false
  globs:
    description: Glob expression(s) of files to lint (newline-delimited)
    default: '*.{md,markdown}'
    required: false
  separator:
    description: String to use as a separator for the "globs" input (defaults to newline)
    default: "\n"
    required: false
runs:
  using: node18
  main: dist/index.js
