name: markdownlint-cli2-action
author: David Anson
description: A GitHub Action to run the markdownlint-cli2 tool for linting Markdown/CommonMark files with the markdownlint library
branding:
  icon: check-square
  color: orange
inputs:
  config:
    description: Path of a file to use for the base configuration object (defaults to none)
    default: ''
    required: false
  fix:
    description: Whether to fix supported issues automatically (any truthy value enables)
    default: ''
    required: false
  globs:
    description: Glob expression(s) of files to lint (newline-delimited)
    default: '*.{md,markdown}'
    required: false
  separator:
    description: String to use as a separator for the "globs" input (defaults to newline)
    default: "\n"
    required: false
runs:
  using: node20
  main: dist/index.mjs
