on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DavidAnson/markdownlint-cli2-action@v3
      with:
        globs: |
          *.md
          !test/*.md
