name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test markdownlint-cli2-action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: No inputs
      uses: ./
