name: Test markdownlint-cli2-action

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test-script:
    name: Run test script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install --no-package-lock
    - run: npm run test
  no-globs:
    name: No globs (README.md, no errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
  one-glob:
    name: One glob (test/errors.md, errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        globs: test/errors.md
  two-globs:
    name: Two globs (README.md and test/errors.md, errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        globs: |
          *.md
          test/*
  command-config:
    name: Command = config (test/errors.md, errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: config
        globs: |
          config/.markdownlint.jsonc
          test/*
  command-config-missing:
    name: Command = config (missing configuration file)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: config
  command-fix:
    name: Command = fix (test/errors.md, no errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: fix
  command-unsupported:
    name: Command = unsupported (fails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        command: unsupported
