name: Test markdownlint-cli2-action

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  no-globs:
    name: No globs (README.md, no errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
  one-glob:
    name: One glob (test/errors.md, errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        globs: test/errors.md
  two-globs:
    name: Two globs (README.md and test/errors.md, errors)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        globs: |
          *.md
          test/*
